// questionsData.js

const QuestionsData = {

  1: [
    { id: 1, question: "The sky is ____.", options: ["blue", "happy", "cold", "rainy"], answer: "blue" },
    { id: 2, question: "I eat ____ for breakfast.", options: ["eggs", "books", "cars", "trees"], answer: "eggs" },
    { id: 3, question: "Dogs can ____.", options: ["bark", "write", "sing", "fly"], answer: "bark" },
    { id: 4, question: "Fish can ____ in water.", options: ["swim", "walk", "run", "jump"], answer: "swim" },
    { id: 5, question: "The sun is ____.", options: ["hot", "cold", "dark", "wet"], answer: "hot" },
    { id: 6, question: "Birds can ____.", options: ["fly", "swim", "drive", "climb"], answer: "fly" },
    { id: 7, question: "We use a ____ to write.", options: ["pen", "shoe", "tree", "shirt"], answer: "pen" },
    { id: 8, question: "You wear ____ on your feet.", options: ["shoes", "hat", "glasses", "gloves"], answer: "shoes" },
    { id: 9, question: "Ice is ____.", options: ["cold", "hot", "heavy", "soft"], answer: "cold" },
    { id: 10, question: "The opposite of hot is ____.", options: ["cold", "warm", "blue", "light"], answer: "cold" },
    { id: 11, question: "We use a ____ to cut things.", options: ["knife", "cup", "book", "pen"], answer: "knife" },
    { id: 12, question: "The moon shines at ____.", options: ["night", "morning", "noon", "dusk"], answer: "night" },
    { id: 13, question: "The opposite of big is ____.", options: ["small", "huge", "tall", "bright"], answer: "small" },
    { id: 14, question: "We drink ____ when we are thirsty.", options: ["water", "salt", "fire", "sand"], answer: "water" },
    { id: 15, question: "Cows give us ____.", options: ["milk", "soda", "juice", "water"], answer: "milk" },
    { id: 16, question: "You can find books in a ____.", options: ["library", "kitchen", "garage", "garden"], answer: "library" },
    { id: 17, question: "We see with our ____.", options: ["eyes", "ears", "nose", "mouth"], answer: "eyes" },
    { id: 18, question: "Cars run on ____.", options: ["fuel", "water", "sand", "electricity"], answer: "fuel" },
    { id: 19, question: "The earth is ____.", options: ["round", "square", "flat", "triangular"], answer: "round" },
    { id: 20, question: "A cat says ____.", options: ["meow", "bark", "moo", "neigh"], answer: "meow" },
    { id: 21, question: "The color of grass is ____.", options: ["green", "blue", "red", "black"], answer: "green" },
    { id: 22, question: "We wear ____ on our hands in winter.", options: ["gloves", "socks", "glasses", "hats"], answer: "gloves" },
    { id: 23, question: "You ____ with your mouth.", options: ["eat", "see", "hear", "feel"], answer: "eat" },
    { id: 24, question: "Leaves are usually ____.", options: ["green", "purple", "orange", "black"], answer: "green" },
    { id: 25, question: "The opposite of fast is ____.", options: ["slow", "quick", "loud", "sharp"], answer: "slow" },
    { id: 26, question: "We use an umbrella when it ____.", options: ["rains", "snows", "is sunny", "is windy"], answer: "rains" },
    { id: 27, question: "A dog has ____ legs.", options: ["four", "two", "six", "eight"], answer: "four" },
    { id: 28, question: "The opposite of tall is ____.", options: ["short", "big", "dark", "light"], answer: "short" },
    { id: 29, question: "A fish lives in ____.", options: ["water", "air", "soil", "grass"], answer: "water" },
    { id: 30, question: "The sound of a clock is ____.", options: ["tick-tock", "meow", "buzz", "hiss"], answer: "tick-tock" }
  ],
  2: [
    { id: 1, question: "I have a ____ in my bag.", options: ["pen", "water", "airplane", "shoe"], answer: "pen" },
    { id: 2, question: "He ____ every day.", options: ["runs", "phones", "lamps", "chairs"], answer: "runs" },
    { id: 3, question: "My favorite color is ____.", options: ["blue", "chair", "tall", "water"], answer: "blue" },
    { id: 4, question: "The opposite of 'big' is ____.", options: ["small", "fast", "sun", "table"], answer: "small" },
    { id: 5, question: "We drink ____ when we are thirsty.", options: ["water", "sand", "air", "salt"], answer: "water" },
    { id: 6, question: "I ____ my homework after school.", options: ["do", "eat", "wear", "throw"], answer: "do" },
    { id: 7, question: "Birds can ____ in the sky.", options: ["fly", "swim", "jump", "write"], answer: "fly" },
    { id: 8, question: "The sky is ____ at night.", options: ["dark", "bright", "red", "green"], answer: "dark" },
    { id: 9, question: "We eat food with a ____.", options: ["fork", "pen", "shoe", "paper"], answer: "fork" },
    { id: 10, question: "The opposite of 'hot' is ____.", options: ["cold", "warm", "bright", "wet"], answer: "cold" },
    { id: 11, question: "A fish lives in ____.", options: ["water", "sand", "air", "grass"], answer: "water" },
    { id: 12, question: "Dogs can ____.", options: ["bark", "read", "write", "sing"], answer: "bark" },
    { id: 13, question: "You wear ____ on your feet.", options: ["shoes", "gloves", "hat", "glasses"], answer: "shoes" },
    { id: 14, question: "We use a ____ to write.", options: ["pen", "plate", "shoe", "fork"], answer: "pen" },
    { id: 15, question: "The sun is ____.", options: ["hot", "cold", "dark", "wet"], answer: "hot" },
    { id: 16, question: "We put ____ on bread.", options: ["butter", "water", "paper", "paint"], answer: "butter" },
    { id: 17, question: "The moon shines at ____.", options: ["night", "morning", "afternoon", "noon"], answer: "night" },
    { id: 18, question: "Cats say ____.", options: ["meow", "woof", "buzz", "moo"], answer: "meow" },
    { id: 19, question: "We see with our ____.", options: ["eyes", "ears", "nose", "hands"], answer: "eyes" },
    { id: 20, question: "A dog has ____ legs.", options: ["four", "two", "three", "five"], answer: "four" },
    { id: 21, question: "Ice is ____.", options: ["cold", "hot", "heavy", "soft"], answer: "cold" },
    { id: 22, question: "We go to the ____ to borrow books.", options: ["library", "store", "beach", "park"], answer: "library" },
    { id: 23, question: "A car runs on ____.", options: ["fuel", "water", "sand", "grass"], answer: "fuel" },
    { id: 24, question: "Cows give us ____.", options: ["milk", "juice", "soda", "water"], answer: "milk" },
    { id: 25, question: "The earth is ____.", options: ["round", "flat", "square", "triangular"], answer: "round" },
    { id: 26, question: "A tree has ____.", options: ["leaves", "wings", "scales", "fins"], answer: "leaves" },
    { id: 27, question: "You drink soup with a ____.", options: ["spoon", "fork", "pen", "plate"], answer: "spoon" },
    { id: 28, question: "The grass is ____.", options: ["green", "blue", "black", "red"], answer: "green" },
    { id: 29, question: "A clock goes ____.", options: ["tick-tock", "woof", "meow", "beep"], answer: "tick-tock" },
    { id: 30, question: "The opposite of 'fast' is ____.", options: ["slow", "quick", "warm", "bright"], answer: "slow" }
  ],
      3: [
        { id: 1, question: "She likes to drink ____ in the morning.", options: ["coffee", "book", "grass", "floor"], answer: "coffee" },
        { id: 2, question: "The opposite of big is ____.", options: ["small", "car", "table", "sun"], answer: "small" },
        { id: 3, question: "I want to go to the ____ for a swim.", options: ["beach", "forest", "mountain", "desert"], answer: "beach" },
        { id: 4, question: "We write with a ____.", options: ["pen", "shoe", "fork", "spoon"], answer: "pen" },
        { id: 5, question: "The sun sets in the ____.", options: ["west", "north", "east", "south"], answer: "west" },
        { id: 6, question: "The opposite of cold is ____.", options: ["hot", "slow", "soft", "hard"], answer: "hot" },
        { id: 7, question: "We see with our ____.", options: ["eyes", "ears", "nose", "mouth"], answer: "eyes" },
        { id: 8, question: "Birds can ____.", options: ["fly", "swim", "drive", "sing"], answer: "fly" },
        { id: 9, question: "A cat says ____.", options: ["meow", "bark", "buzz", "quack"], answer: "meow" },
        { id: 10, question: "A ____ is used to cut things.", options: ["knife", "cup", "pen", "book"], answer: "knife" },
        { id: 11, question: "The color of the sky is often ____.", options: ["blue", "green", "yellow", "red"], answer: "blue" },
        { id: 12, question: "We wear ____ on our feet.", options: ["shoes", "gloves", "hats", "scarves"], answer: "shoes" },
        { id: 13, question: "Water turns to ice when it is ____.", options: ["cold", "hot", "heavy", "soft"], answer: "cold" },
        { id: 14, question: "A tree has ____.", options: ["leaves", "feathers", "scales", "wheels"], answer: "leaves" },
        { id: 15, question: "The opposite of light is ____.", options: ["dark", "bright", "happy", "big"], answer: "dark" },
        { id: 16, question: "The ____ is bright in the sky during the day.", options: ["sun", "moon", "star", "cloud"], answer: "sun" },
        { id: 17, question: "We use a ____ to eat soup.", options: ["spoon", "fork", "knife", "pen"], answer: "spoon" },
        { id: 18, question: "Cows give us ____.", options: ["milk", "soda", "juice", "water"], answer: "milk" },
        { id: 19, question: "We eat breakfast in the ____.", options: ["morning", "afternoon", "evening", "night"], answer: "morning" },
        { id: 20, question: "A ____ is an animal that can fly.", options: ["bird", "fish", "lion", "tiger"], answer: "bird" },
        { id: 21, question: "The opposite of happy is ____.", options: ["sad", "tall", "soft", "quiet"], answer: "sad" },
        { id: 22, question: "You ____ food with your mouth.", options: ["eat", "see", "hear", "walk"], answer: "eat" },
        { id: 23, question: "Fish live in ____.", options: ["water", "trees", "sky", "grass"], answer: "water" },
        { id: 24, question: "The opposite of fast is ____.", options: ["slow", "quick", "bright", "sharp"], answer: "slow" },
        { id: 25, question: "We wear ____ on our hands in the winter.", options: ["gloves", "socks", "hats", "shoes"], answer: "gloves" },
        { id: 26, question: "Cars run on ____.", options: ["fuel", "water", "sand", "air"], answer: "fuel" },
        { id: 27, question: "A bicycle has ____ wheels.", options: ["two", "three", "four", "five"], answer: "two" },
        { id: 28, question: "We can ____ a book.", options: ["read", "eat", "write", "swim"], answer: "read" },
        { id: 29, question: "The color of grass is ____.", options: ["green", "blue", "red", "black"], answer: "green" },
        { id: 30, question: "The opposite of 'up' is ____.", options: ["down", "left", "right", "near"], answer: "down" }
      ],

      4: [
        { id: 1, question: "I need to ____ my homework.", options: ["do", "take", "make", "build"], answer: "do" },
        { id: 2, question: "He ____ to the park every day.", options: ["goes", "drives", "flies", "walks"], answer: "goes" },
        { id: 3, question: "We had a great time at the ____.", options: ["beach", "car", "moon", "tree"], answer: "beach" },
        { id: 4, question: "She likes to ____ stories.", options: ["read", "build", "drive", "sing"], answer: "read" },
        { id: 5, question: "The opposite of 'cold' is ____.", options: ["hot", "warm", "soft", "blue"], answer: "hot" },
        { id: 6, question: "We ____ food with a fork.", options: ["eat", "play", "read", "hear"], answer: "eat" },
        { id: 7, question: "He ____ his bike every weekend.", options: ["rides", "drives", "flies", "cooks"], answer: "rides" },
        { id: 8, question: "A tree has many ____.", options: ["leaves", "legs", "wheels", "nails"], answer: "leaves" },
        { id: 9, question: "We listen to music with our ____.", options: ["ears", "eyes", "nose", "mouth"], answer: "ears" },
        { id: 10, question: "She ____ a beautiful picture.", options: ["draws", "drives", "wears", "eats"], answer: "draws" },
        { id: 11, question: "They ____ their car every Saturday.", options: ["wash", "ride", "read", "draw"], answer: "wash" },
        { id: 12, question: "The moon is visible at ____.", options: ["night", "noon", "morning", "dawn"], answer: "night" },
        { id: 13, question: "We ____ TV to watch shows.", options: ["turn on", "open", "ride", "hear"], answer: "turn on" },
        { id: 14, question: "The opposite of 'fast' is ____.", options: ["slow", "quick", "bright", "heavy"], answer: "slow" },
        { id: 15, question: "He ____ his dog every morning.", options: ["feeds", "drinks", "writes", "drives"], answer: "feeds" },
        { id: 16, question: "A book has many ____.", options: ["pages", "ears", "leaves", "walls"], answer: "pages" },
        { id: 17, question: "We wear ____ on our hands in winter.", options: ["gloves", "socks", "hats", "scarves"], answer: "gloves" },
        { id: 18, question: "They ____ a movie on Friday nights.", options: ["watch", "hear", "drive", "sing"], answer: "watch" },
        { id: 19, question: "The opposite of 'happy' is ____.", options: ["sad", "tall", "bright", "quiet"], answer: "sad" },
        { id: 20, question: "A car has ____ wheels.", options: ["four", "three", "two", "five"], answer: "four" },
        { id: 21, question: "We ____ food when we are hungry.", options: ["eat", "see", "listen", "sing"], answer: "eat" },
        { id: 22, question: "He ____ to school every day.", options: ["walks", "cooks", "listens", "draws"], answer: "walks" },
        { id: 23, question: "The opposite of 'up' is ____.", options: ["down", "left", "right", "near"], answer: "down" },
        { id: 24, question: "We see with our ____.", options: ["eyes", "ears", "nose", "hands"], answer: "eyes" },
        { id: 25, question: "The earth is ____.", options: ["round", "flat", "square", "triangle"], answer: "round" },
        { id: 26, question: "Fish live in ____.", options: ["water", "air", "soil", "sand"], answer: "water" },
        { id: 27, question: "The color of grass is ____.", options: ["green", "blue", "black", "red"], answer: "green" },
        { id: 28, question: "She ____ her friend a gift.", options: ["gives", "sings", "draws", "sees"], answer: "gives" },
        { id: 29, question: "We ____ the door when we leave.", options: ["close", "listen", "jump", "draw"], answer: "close" },
        { id: 30, question: "The opposite of 'day' is ____.", options: ["night", "morning", "noon", "evening"], answer: "night" }
      ],
        
      5: [
        { id: 1, question: "She ____ a beautiful song.", options: ["sings", "paints", "writes", "reads"], answer: "sings" },
        { id: 2, question: "The opposite of 'cold' is ____.", options: ["hot", "warm", "cool", "wet"], answer: "hot" },
        { id: 3, question: "They ____ football every weekend.", options: ["play", "run", "jump", "sing"], answer: "play" },
        { id: 4, question: "We ____ to music when we relax.", options: ["listen", "watch", "eat", "feel"], answer: "listen" },
        { id: 5, question: "A farmer grows ____.", options: ["crops", "cars", "houses", "shoes"], answer: "crops" },
        { id: 6, question: "The sun rises in the ____.", options: ["east", "west", "north", "south"], answer: "east" },
        { id: 7, question: "She ____ her clothes every morning.", options: ["wears", "eats", "throws", "draws"], answer: "wears" },
        { id: 8, question: "The opposite of 'happy' is ____.", options: ["sad", "tall", "quiet", "small"], answer: "sad" },
        { id: 9, question: "Fish live in ____.", options: ["water", "air", "soil", "trees"], answer: "water" },
        { id: 10, question: "We use a ____ to cut paper.", options: ["scissors", "spoon", "fork", "cup"], answer: "scissors" },
        { id: 11, question: "She ____ the door before leaving.", options: ["closes", "eats", "wears", "drinks"], answer: "closes" },
        { id: 12, question: "The opposite of 'up' is ____.", options: ["down", "left", "over", "high"], answer: "down" },
        { id: 13, question: "The opposite of 'night' is ____.", options: ["day", "morning", "dawn", "dark"], answer: "day" },
        { id: 14, question: "We put ____ on bread to make a sandwich.", options: ["butter", "paper", "water", "salt"], answer: "butter" },
        { id: 15, question: "The color of the sky is often ____.", options: ["blue", "green", "yellow", "red"], answer: "blue" },
        { id: 16, question: "We drink ____ when we are thirsty.", options: ["water", "salt", "fire", "sand"], answer: "water" },
        { id: 17, question: "A bicycle has ____ wheels.", options: ["two", "three", "four", "five"], answer: "two" },
        { id: 18, question: "The opposite of 'fast' is ____.", options: ["slow", "quick", "warm", "bright"], answer: "slow" },
        { id: 19, question: "We see with our ____.", options: ["eyes", "ears", "nose", "hands"], answer: "eyes" },
        { id: 20, question: "A dog has ____ legs.", options: ["four", "two", "three", "five"], answer: "four" },
        { id: 21, question: "We read a ____ to learn information.", options: ["book", "song", "plate", "tree"], answer: "book" },
        { id: 22, question: "We ____ a sweater when it is cold.", options: ["wear", "see", "listen", "write"], answer: "wear" },
        { id: 23, question: "We ____ our teeth twice a day.", options: ["brush", "wash", "wear", "see"], answer: "brush" },
        { id: 24, question: "The opposite of 'near' is ____.", options: ["far", "close", "tall", "low"], answer: "far" },
        { id: 25, question: "You ____ food with a fork.", options: ["eat", "write", "draw", "wash"], answer: "eat" },
        { id: 26, question: "The opposite of 'big' is ____.", options: ["small", "near", "loud", "soft"], answer: "small" },
        { id: 27, question: "We write in a ____.", options: ["notebook", "kitchen", "car", "sky"], answer: "notebook" },
        { id: 28, question: "A cow says ____.", options: ["moo", "meow", "quack", "buzz"], answer: "moo" },
        { id: 29, question: "The sun sets in the ____.", options: ["west", "north", "east", "south"], answer: "west" },
        { id: 30, question: "We use a ____ to see things far away.", options: ["binoculars", "pencil", "mirror", "glass"], answer: "binoculars" }
      ],
      6: [
        { id: 1, audio: "/audio/level6-question1.mp3", question: "I have a ____ in my hand.", options: ["pen", "apple", "tree", "car"], answer: "pen" },
        { id: 2, audio: "/audio/level6-question2.mp3", question: "The child ____ with his toy.", options: ["plays", "eats", "drinks", "sleeps"], answer: "plays" },
        { id: 3, audio: "/audio/level6-question3.mp3", question: "She ____ at the sky.", options: ["looks", "writes", "cooks", "builds"], answer: "looks" },
        { id: 4, audio: "/audio/level6-question4.mp3", question: "He ____ breakfast every morning.", options: ["eats", "drinks", "reads", "writes"], answer: "eats" },
        { id: 5, audio: "/audio/level6-question5.mp3", question: "The opposite of 'open' is ____.", options: ["close", "start", "jump", "see"], answer: "close" },
        { id: 6, audio: "/audio/level6-question6.mp3", question: "A bird can ____.", options: ["fly", "swim", "walk", "run"], answer: "fly" },
        { id: 7, audio: "/audio/level6-question7.mp3", question: "We ____ water when we are thirsty.", options: ["drink", "write", "draw", "eat"], answer: "drink" },
        { id: 8, audio: "/audio/level6-question8.mp3", question: "The sun sets in the ____.", options: ["west", "north", "east", "south"], answer: "west" },
        { id: 9, audio: "/audio/level6-question9.mp3", question: "She ____ a letter to her friend.", options: ["writes", "reads", "listens", "paints"], answer: "writes" },
        { id: 10, audio: "/audio/level6-question10.mp3", question: "The opposite of 'day' is ____.", options: ["night", "morning", "dawn", "sunset"], answer: "night" },
        { id: 11, audio: "/audio/level6-question11.mp3", question: "We use a ____ to see small things.", options: ["magnifier", "pen", "cup", "knife"], answer: "magnifier" },
        { id: 12, audio: "/audio/level6-question12.mp3", question: "We ____ in a bed at night.", options: ["sleep", "jump", "eat", "dance"], answer: "sleep" },
        { id: 13, audio: "/audio/level6-question13.mp3", question: "She ____ her shoes before going out.", options: ["wears", "drinks", "draws", "sees"], answer: "wears" },
        { id: 14, audio: "/audio/level6-question14.mp3", question: "The color of the ocean is often ____.", options: ["blue", "red", "yellow", "black"], answer: "blue" },
        { id: 15, audio: "/audio/level6-question15.mp3", question: "We ____ to music when we relax.", options: ["listen", "read", "cook", "see"], answer: "listen" },
        { id: 16, audio: "/audio/level6-question16.mp3", question: "She ____ her friend with her homework.", options: ["helps", "eats", "jumps", "washes"], answer: "helps" },
        { id: 17, audio: "/audio/level6-question17.mp3", question: "We write with a ____.", options: ["pen", "cup", "fork", "shoe"], answer: "pen" },
        { id: 18, audio: "/audio/level6-question18.mp3", question: "The opposite of 'happy' is ____.", options: ["sad", "big", "dark", "quiet"], answer: "sad" },
        { id: 19, audio: "/audio/level6-question19.mp3", question: "Birds have ____ to fly.", options: ["wings", "legs", "tails", "noses"], answer: "wings" },
        { id: 20, audio: "/audio/level6-question20.mp3", question: "We read a ____ to learn.", options: ["book", "song", "plate", "shoe"], answer: "book" },
        { id: 21, audio: "/audio/level6-question21.mp3", question: "We ____ on a chair.", options: ["sit", "jump", "run", "sleep"], answer: "sit" },
        { id: 22, audio: "/audio/level6-question22.mp3", question: "A cat says ____.", options: ["meow", "woof", "moo", "quack"], answer: "meow" },
        { id: 23, audio: "/audio/level6-question23.mp3", question: "The opposite of 'tall' is ____.", options: ["short", "big", "high", "dark"], answer: "short" },
        { id: 24, audio: "/audio/level6-question24.mp3", question: "The opposite of 'fast' is ____.", options: ["slow", "quick", "tall", "loud"], answer: "slow" },
        { id: 25, audio: "/audio/level6-question25.mp3", question: "A cow gives us ____.", options: ["milk", "water", "juice", "oil"], answer: "milk" },
        { id: 26, audio: "/audio/level6-question26.mp3", question: "The sky is often ____ during the day.", options: ["blue", "green", "red", "black"], answer: "blue" },
        { id: 27, audio: "/audio/level6-question27.mp3", question: "You ____ food with a spoon.", options: ["eat", "read", "draw", "run"], answer: "eat" },
        { id: 28, audio: "/audio/level6-question28.mp3", question: "The opposite of 'new' is ____.", options: ["old", "young", "high", "small"], answer: "old" },
        { id: 29, audio: "/audio/level6-question29.mp3", question: "We use a ____ to clean our teeth.", options: ["toothbrush", "fork", "shoe", "comb"], answer: "toothbrush" },
        { id: 30, audio: "/audio/level6-question30.mp3", question: "We ____ our hands before eating.", options: ["wash", "read", "draw", "write"], answer: "wash" }
    ],
      
    7: [
      { id: 1, audio: "/audio/level7-question1.mp3", question: "I would like some ____ to drink.", options: ["water", "table", "carpet", "sky"], answer: "water" },
      { id: 2, audio: "/audio/level7-question2.mp3", question: "The ____ is bright at night.", options: ["moon", "car", "glass", "sand"], answer: "moon" },
      { id: 3, audio: "/audio/level7-question3.mp3", question: "She ____ when she is happy.", options: ["smiles", "climbs", "throws", "reads"], answer: "smiles" },
      { id: 4, audio: "/audio/level7-question4.mp3", question: "The opposite of fast is ____.", options: ["slow", "quick", "tall", "short"], answer: "slow" },
      { id: 5, audio: "/audio/level7-question5.mp3", question: "He ____ the book carefully.", options: ["reads", "throws", "jumps", "drinks"], answer: "reads" },
      { id: 6, audio: "/audio/level7-question6.mp3", question: "You can write with a ____.", options: ["pen", "shoe", "tree", "cup"], answer: "pen" },
      { id: 7, audio: "/audio/level7-question7.mp3", question: "Birds can ____ in the sky.", options: ["fly", "run", "swim", "jump"], answer: "fly" },
      { id: 8, audio: "/audio/level7-question8.mp3", question: "We eat with a ____.", options: ["spoon", "pen", "book", "phone"], answer: "spoon" },
      { id: 9, audio: "/audio/level7-question9.mp3", question: "The opposite of night is ____.", options: ["day", "evening", "moon", "dark"], answer: "day" },
      { id: 10, audio: "/audio/level7-question10.mp3", question: "A dog says ____.", options: ["bark", "meow", "buzz", "moo"], answer: "bark" },
      { id: 11, audio: "/audio/level7-question11.mp3", question: "The sun rises in the ____.", options: ["east", "west", "north", "south"], answer: "east" },
      { id: 12, audio: "/audio/level7-question12.mp3", question: "You wear ____ on your feet.", options: ["shoes", "hats", "gloves", "jackets"], answer: "shoes" },
      { id: 13, audio: "/audio/level7-question13.mp3", question: "Ice is ____.", options: ["cold", "hot", "soft", "dry"], answer: "cold" },
      { id: 14, audio: "/audio/level7-question14.mp3", question: "We see with our ____.", options: ["eyes", "ears", "nose", "mouth"], answer: "eyes" },
      { id: 15, audio: "/audio/level7-question15.mp3", question: "The color of grass is ____.", options: ["green", "red", "blue", "black"], answer: "green" },
      { id: 16, audio: "/audio/level7-question16.mp3", question: "The opposite of hot is ____.", options: ["cold", "warm", "high", "blue"], answer: "cold" },
      { id: 17, audio: "/audio/level7-question17.mp3", question: "You ____ food when you are hungry.", options: ["eat", "throw", "play", "run"], answer: "eat" },
      { id: 18, audio: "/audio/level7-question18.mp3", question: "Cars run on ____.", options: ["fuel", "water", "air", "grass"], answer: "fuel" },
      { id: 19, audio: "/audio/level7-question19.mp3", question: "Fish can ____ in water.", options: ["swim", "jump", "fly", "run"], answer: "swim" },
      { id: 20, audio: "/audio/level7-question20.mp3", question: "The earth is ____.", options: ["round", "flat", "square", "triangular"], answer: "round" },
      { id: 21, audio: "/audio/level7-question21.mp3", question: "The opposite of up is ____.", options: ["down", "over", "near", "left"], answer: "down" },
      { id: 22, audio: "/audio/level7-question22.mp3", question: "We use an umbrella when it ____.", options: ["rains", "snows", "is hot", "is windy"], answer: "rains" },
      { id: 23, audio: "/audio/level7-question23.mp3", question: "A cat says ____.", options: ["meow", "bark", "buzz", "roar"], answer: "meow" },
      { id: 24, audio: "/audio/level7-question24.mp3", question: "A dog has ____ legs.", options: ["four", "two", "six", "eight"], answer: "four" },
      { id: 25, audio: "/audio/level7-question25.mp3", question: "We wear ____ on our hands in winter.", options: ["gloves", "shoes", "hats", "scarves"], answer: "gloves" },
      { id: 26, audio: "/audio/level7-question26.mp3", question: "Leaves are usually ____.", options: ["green", "orange", "purple", "white"], answer: "green" },
      { id: 27, audio: "/audio/level7-question27.mp3", question: "You ____ with your mouth.", options: ["eat", "see", "feel", "hear"], answer: "eat" },
      { id: 28, audio: "/audio/level7-question28.mp3", question: "The opposite of tall is ____.", options: ["short", "big", "dark", "light"], answer: "short" },
      { id: 29, audio: "/audio/level7-question29.mp3", question: "A fish lives in ____.", options: ["water", "air", "soil", "grass"], answer: "water" },
      { id: 30, audio: "/audio/level7-question30.mp3", question: "The sound of a clock is ____.", options: ["tick-tock", "meow", "buzz", "hiss"], answer: "tick-tock" }
    ],
    8: [
      { id: 1, audio: "/audio/level8-question1.mp3", question: "The sun rises in the ____.", options: ["east", "west", "north", "south"], answer: "east" },
      { id: 2, audio: "/audio/level8-question2.mp3", question: "They ____ the book yesterday.", options: ["read", "run", "drive", "swim"], answer: "read" },
      { id: 3, audio: "/audio/level8-question3.mp3", question: "I ____ him since last year.", options: ["have known", "know", "knew", "am knowing"], answer: "have known" },
      { id: 4, audio: "/audio/level8-question4.mp3", question: "She ____ a letter every month.", options: ["writes", "sings", "builds", "runs"], answer: "writes" },
      { id: 5, audio: "/audio/level8-question5.mp3", question: "The opposite of early is ____.", options: ["late", "soon", "fast", "slow"], answer: "late" },
      { id: 6, audio: "/audio/level8-question6.mp3", question: "They ____ here since 2010.", options: ["have lived", "live", "lived", "are living"], answer: "have lived" },
      { id: 7, audio: "/audio/level8-question7.mp3", question: "He ____ his homework before dinner.", options: ["finished", "finishes", "will finish", "finish"], answer: "finished" },
      { id: 8, audio: "/audio/level8-question8.mp3", question: "We ____ a movie last night.", options: ["watched", "watch", "watches", "are watching"], answer: "watched" },
      { id: 9, audio: "/audio/level8-question9.mp3", question: "The ____ of the book was surprising.", options: ["end", "beginning", "cover", "author"], answer: "end" },
      { id: 10, audio: "/audio/level8-question10.mp3", question: "They ____ to the gym every day.", options: ["go", "went", "going", "gone"], answer: "go" },
      { id: 11, audio: "/audio/level8-question11.mp3", question: "We ____ dinner when he arrived.", options: ["were having", "have", "had", "has"], answer: "were having" },
      { id: 12, audio: "/audio/level8-question12.mp3", question: "She ____ all her exams last week.", options: ["passed", "passes", "pass", "passing"], answer: "passed" },
      { id: 13, audio: "/audio/level8-question13.mp3", question: "The teacher ____ us a new topic today.", options: ["taught", "teach", "teaches", "is teaching"], answer: "taught" },
      { id: 14, audio: "/audio/level8-question14.mp3", question: "They ____ to a new city next year.", options: ["will move", "move", "moved", "moving"], answer: "will move" },
      { id: 15, audio: "/audio/level8-question15.mp3", question: "She ____ the song beautifully.", options: ["sings", "sing", "sang", "is singing"], answer: "sang" },
      { id: 16, audio: "/audio/level8-question16.mp3", question: "We ____ a lot during the trip.", options: ["learned", "learn", "learning", "learns"], answer: "learned" },
      { id: 17, audio: "/audio/level8-question17.mp3", question: "He ____ to school every morning.", options: ["walks", "walked", "walking", "walk"], answer: "walks" },
      { id: 18, audio: "/audio/level8-question18.mp3", question: "The movie ____ interesting.", options: ["was", "is", "are", "be"], answer: "was" },
      { id: 19, audio: "/audio/level8-question19.mp3", question: "They ____ lunch at noon.", options: ["have", "has", "having", "had"], answer: "have" },
      { id: 20, audio: "/audio/level8-question20.mp3", question: "We ____ our friends yesterday.", options: ["visited", "visit", "visits", "are visiting"], answer: "visited" },
      { id: 21, audio: "/audio/level8-question21.mp3", question: "He ____ a new book every month.", options: ["reads", "read", "reading", "have read"], answer: "reads" },
      { id: 22, audio: "/audio/level8-question22.mp3", question: "They ____ in the park last weekend.", options: ["played", "play", "playing", "plays"], answer: "played" },
      { id: 23, audio: "/audio/level8-question23.mp3", question: "She ____ for an hour every day.", options: ["exercises", "exercise", "exercised", "exercising"], answer: "exercises" },
      { id: 24, audio: "/audio/level8-question24.mp3", question: "We ____ to the concert last night.", options: ["went", "go", "going", "gone"], answer: "went" },
      { id: 25, audio: "/audio/level8-question25.mp3", question: "He ____ a song yesterday.", options: ["wrote", "write", "writing", "writes"], answer: "wrote" },
      { id: 26, audio: "/audio/level8-question26.mp3", question: "They ____ breakfast at 8 am.", options: ["have", "had", "has", "having"], answer: "have" },
      { id: 27, audio: "/audio/level8-question27.mp3", question: "She ____ the answer correctly.", options: ["knew", "know", "knowing", "knows"], answer: "knew" },
      { id: 28, audio: "/audio/level8-question28.mp3", question: "The book ____ very interesting.", options: ["is", "are", "was", "be"], answer: "is" },
      { id: 29, audio: "/audio/level8-question29.mp3", question: "We ____ to finish the project.", options: ["need", "needed", "needs", "are needing"], answer: "need" },
      { id: 30, audio: "/audio/level8-question30.mp3", question: "They ____ him about the news.", options: ["told", "tell", "telling", "tells"], answer: "told" }
    ],
      
    9: [
      { id: 1, audio: "/audio/level9-question1.mp3", question: "They are planning to ____ a house.", options: ["build", "see", "drive", "climb"], answer: "build" },
      { id: 2, audio: "/audio/level9-question2.mp3", question: "He was ____ by the noise.", options: ["disturbed", "created", "built", "sung"], answer: "disturbed" },
      { id: 3, audio: "/audio/level9-question3.mp3", question: "She ____ a new job next month.", options: ["starts", "starts", "started", "starting"], answer: "starts" },
      { id: 4, audio: "/audio/level9-question4.mp3", question: "The project was ____ yesterday.", options: ["completed", "begun", "canceled", "extended"], answer: "completed" },
      { id: 5, audio: "/audio/level9-question5.mp3", question: "He ____ the painting on the wall.", options: ["hung", "placed", "wrote", "spoke"], answer: "hung" },
      { id: 6, audio: "/audio/level9-question6.mp3", question: "The sun ____ in the west.", options: ["sets", "rises", "falls", "stays"], answer: "sets" },
      { id: 7, audio: "/audio/level9-question7.mp3", question: "She was ____ for her hard work.", options: ["praised", "criticized", "ignored", "overlooked"], answer: "praised" },
      { id: 8, audio: "/audio/level9-question8.mp3", question: "They have ____ the changes.", options: ["accepted", "denied", "avoided", "forgotten"], answer: "accepted" },
      { id: 9, audio: "/audio/level9-question9.mp3", question: "We ____ the documents by mail.", options: ["sent", "read", "received", "ignored"], answer: "sent" },
      { id: 10, audio: "/audio/level9-question10.mp3", question: "The book was ____ from Spanish.", options: ["translated", "rewritten", "spoken", "corrected"], answer: "translated" },
      { id: 11, audio: "/audio/level9-question11.mp3", question: "The cake was ____ quickly.", options: ["eaten", "baked", "frozen", "melted"], answer: "eaten" },
      { id: 12, audio: "/audio/level9-question12.mp3", question: "He ____ his team with confidence.", options: ["led", "follows", "ignored", "avoided"], answer: "led" },
      { id: 13, audio: "/audio/level9-question13.mp3", question: "They ____ a new method last year.", options: ["developed", "ended", "dismissed", "forgot"], answer: "developed" },
      { id: 14, audio: "/audio/level9-question14.mp3", question: "The bridge was ____ two years ago.", options: ["built", "destroyed", "skipped", "repaired"], answer: "built" },
      { id: 15, audio: "/audio/level9-question15.mp3", question: "He ____ the package in the car.", options: ["left", "brought", "sent", "took"], answer: "left" },
      { id: 16, audio: "/audio/level9-question16.mp3", question: "The meeting will be ____ next week.", options: ["held", "ended", "dismissed", "started"], answer: "held" },
      { id: 17, audio: "/audio/level9-question17.mp3", question: "They ____ all the tickets.", options: ["sold", "bought", "printed", "found"], answer: "sold" },
      { id: 18, audio: "/audio/level9-question18.mp3", question: "The plan was ____ by the manager.", options: ["approved", "rejected", "ignored", "delayed"], answer: "approved" },
      { id: 19, audio: "/audio/level9-question19.mp3", question: "She was ____ by her friends.", options: ["supported", "avoided", "forgotten", "rejected"], answer: "supported" },
      { id: 20, audio: "/audio/level9-question20.mp3", question: "They ____ the news to everyone.", options: ["announced", "hid", "avoided", "changed"], answer: "announced" },
      { id: 21, audio: "/audio/level9-question21.mp3", question: "The rules were ____ last month.", options: ["changed", "broken", "ignored", "created"], answer: "changed" },
      { id: 22, audio: "/audio/level9-question22.mp3", question: "He ____ his project with pride.", options: ["finished", "avoided", "destroyed", "began"], answer: "finished" },
      { id: 23, audio: "/audio/level9-question23.mp3", question: "The storm ____ all the crops.", options: ["destroyed", "saved", "grew", "avoided"], answer: "destroyed" },
      { id: 24, audio: "/audio/level9-question24.mp3", question: "The artist ____ a new painting.", options: ["created", "sold", "lost", "avoided"], answer: "created" },
      { id: 25, audio: "/audio/level9-question25.mp3", question: "The students were ____ at noon.", options: ["dismissed", "called", "arrived", "taken"], answer: "dismissed" },
      { id: 26, audio: "/audio/level9-question26.mp3", question: "The car was ____ by a mechanic.", options: ["repaired", "sold", "painted", "driven"], answer: "repaired" },
      { id: 27, audio: "/audio/level9-question27.mp3", question: "The flowers were ____ in spring.", options: ["planted", "grown", "built", "bought"], answer: "planted" },
      { id: 28, audio: "/audio/level9-question28.mp3", question: "He ____ the interview with confidence.", options: ["passed", "failed", "avoided", "attended"], answer: "passed" },
      { id: 29, audio: "/audio/level9-question29.mp3", question: "They ____ the journey at dawn.", options: ["began", "ended", "avoided", "arrived"], answer: "began" },
      { id: 30, audio: "/audio/level9-question30.mp3", question: "The shop was ____ last week.", options: ["opened", "closed", "ignored", "seen"], answer: "opened" }
    ],  
    10: [
      { id: 1, audio: "/audio/level10-question1.mp3", question: "The decision was ____ by everyone.", options: ["accepted", "denied", "questioned", "avoided"], answer: "accepted" },
      { id: 2, audio: "/audio/level10-question2.mp3", question: "They are known for their ____ innovation.", options: ["remarkable", "usual", "typical", "familiar"], answer: "remarkable" },
      { id: 3, audio: "/audio/level10-question3.mp3", question: "He ____ his job due to personal reasons.", options: ["left", "leaves", "will leave", "has left"], answer: "left" },
      { id: 4, audio: "/audio/level10-question4.mp3", question: "The results were ____ as expected.", options: ["positive", "negative", "different", "similar"], answer: "positive" },
      { id: 5, audio: "/audio/level10-question5.mp3", question: "She was ____ with the project outcome.", options: ["satisfied", "dissatisfied", "ignored", "amazed"], answer: "satisfied" },
      { id: 6, audio: "/audio/level10-question6.mp3", question: "He ____ his plan to improve the system.", options: ["proposed", "rejected", "ignored", "avoided"], answer: "proposed" },
      { id: 7, audio: "/audio/level10-question7.mp3", question: "They ____ their success to hard work.", options: ["attribute", "ignore", "deny", "reduce"], answer: "attribute" },
      { id: 8, audio: "/audio/level10-question8.mp3", question: "The company ____ its goals last year.", options: ["achieved", "avoided", "lost", "failed"], answer: "achieved" },
      { id: 9, audio: "/audio/level10-question9.mp3", question: "She ____ the project with a team.", options: ["managed", "ignored", "avoided", "refused"], answer: "managed" },
      { id: 10, audio: "/audio/level10-question10.mp3", question: "The issue was ____ during the meeting.", options: ["discussed", "rejected", "denied", "ignored"], answer: "discussed" },
      { id: 11, audio: "/audio/level10-question11.mp3", question: "They ____ a major breakthrough.", options: ["achieved", "ignored", "avoided", "left"], answer: "achieved" },
      { id: 12, audio: "/audio/level10-question12.mp3", question: "The report was ____ by all departments.", options: ["approved", "dismissed", "forgotten", "avoided"], answer: "approved" },
      { id: 13, audio: "/audio/level10-question13.mp3", question: "He was ____ for his dedication.", options: ["recognized", "ignored", "avoided", "forgotten"], answer: "recognized" },
      { id: 14, audio: "/audio/level10-question14.mp3", question: "The ____ was announced yesterday.", options: ["decision", "journey", "lesson", "story"], answer: "decision" },
      { id: 15, audio: "/audio/level10-question15.mp3", question: "They ____ the issue thoroughly.", options: ["analyzed", "dismissed", "avoided", "forgot"], answer: "analyzed" },
      { id: 16, audio: "/audio/level10-question16.mp3", question: "She ____ to finish the work on time.", options: ["managed", "refused", "delayed", "denied"], answer: "managed" },
      { id: 17, audio: "/audio/level10-question17.mp3", question: "The policy was ____ last month.", options: ["implemented", "forgotten", "denied", "avoided"], answer: "implemented" },
      { id: 18, audio: "/audio/level10-question18.mp3", question: "He ____ the importance of teamwork.", options: ["emphasized", "ignored", "forgot", "avoided"], answer: "emphasized" },
      { id: 19, audio: "/audio/level10-question19.mp3", question: "The process was ____ for clarity.", options: ["simplified", "complicated", "ignored", "overlooked"], answer: "simplified" },
      { id: 20, audio: "/audio/level10-question20.mp3", question: "The project was ____ on schedule.", options: ["completed", "lost", "missed", "forgotten"], answer: "completed" },
      { id: 21, audio: "/audio/level10-question21.mp3", question: "They ____ the deadline by two days.", options: ["extended", "shortened", "ignored", "denied"], answer: "extended" },
      { id: 22, audio: "/audio/level10-question22.mp3", question: "The report was ____ for accuracy.", options: ["reviewed", "rejected", "ignored", "forgotten"], answer: "reviewed" },
      { id: 23, audio: "/audio/level10-question23.mp3", question: "He ____ his speech to the audience.", options: ["delivered", "forgot", "avoided", "lost"], answer: "delivered" },
      { id: 24, audio: "/audio/level10-question24.mp3", question: "The agreement was ____ by all.", options: ["accepted", "rejected", "ignored", "delayed"], answer: "accepted" },
      { id: 25, audio: "/audio/level10-question25.mp3", question: "The company ____ its competitors.", options: ["outperformed", "followed", "avoided", "ignored"], answer: "outperformed" },
      { id: 26, audio: "/audio/level10-question26.mp3", question: "They ____ a plan for improvement.", options: ["proposed", "avoided", "forgot", "lost"], answer: "proposed" },
      { id: 27, audio: "/audio/level10-question27.mp3", question: "The team was ____ for their success.", options: ["celebrated", "ignored", "dismissed", "forgotten"], answer: "celebrated" },
      { id: 28, audio: "/audio/level10-question28.mp3", question: "The new system was ____ smoothly.", options: ["implemented", "lost", "denied", "ignored"], answer: "implemented" },
      { id: 29, audio: "/audio/level10-question29.mp3", question: "She ____ on the team’s efforts.", options: ["reflected", "avoided", "forgot", "missed"], answer: "reflected" },
      { id: 30, audio: "/audio/level10-question30.mp3", question: "They ____ the proposal carefully.", options: ["considered", "ignored", "forgot", "denied"], answer: "considered" }
    ],
  };
  
  export default QuestionsData;
  